# -*- coding: utf-8 -*-
"""dict , conditional, loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIyXScgysW9qEuqjwf1m28HkClzZJo2o
"""

d = {}

type(d)

d1 = {'key':'sohail'}

d1

d2 = {'name':'sohail','email':'mr.sohailkhan.27@gmail.com','number':'9100381051'}

d2

d3 = {124:'sohail','-var':'kumar', True : 2546}

d3

d3[124]

d3[True]

d3[1]

d3[0]

d4 = {'name':'sohail', 'email':'sk252275426@gmail.com','name':'khan'}

d4

d4['name'] #key should be unique otherwise its over right

"""Values"""

d5 = {'company':'pwskills','courses':['web dev',"java with dsa","system design"]}

d5

d5['courses']

d5['courses'][1]

d6 = {'number':[12,14,15,62,45,11,52],'assignment':(1,2,1,4,1,32,5),"launched date":{28,12,14},"class-Timing":{'web_dev':8,"data science": 9,"java with dsa":7}}

d6

d6['class-Timing']

d6['class-Timing']['java with dsa']

"""adding a key into dict"""

d6['mentor']=["sudhansu","krish"]

d6

d6["Friend"]='Arbaz'

d6

"""Deleting a key"""

del d6['Friend']

d6

d6.keys()

list(d6.keys())

list(d6.values())

list(d6.items())

d6.pop('assignment')

d6



"""### **Conditional statement or decision making statement**"""

marks = int(input("Enter your Marks "))
if marks >= 80:
  print("you will be a part of A0 Batch")
elif marks >= 60 and marks <80:
  print("you will be a part of A1 Batch")
elif marks >= 40 and marks <60:
  print("you will be a part of A2 Batch")
else:
  print("you will be a part of A3 Batch")

price = int(input("enter price"))
if price >1000:
  print("I will not purchase")
else :
  print("I will purchase")

price = int(input("enter price"))
if price >1000:
  print("I will not purchase")

price = int(input("enter price "))
if price >1000:
  print("I will not purchase")
  if price >5000:
    print("price is too much")
  elif price <2000 :
    print("It's okay")
elif price < 1000:
  print("I will purchase")
else :
  print("Not interested")

"""**For loop**"""

l = [1,2,3,4,5,6,7,8]
l1 = []
for i in l:
  print (i+1)
  l1.append(i+1)

l1

l = ["sudh","kumar","kumar","course"]
l1 = []
for i in l:
  print(i)
  l1.append(i.upper())

l = [1,2,3,4,4,"sudh","kumar",124,34,456,"abs"]

#seperate integer and string variables

l1_num = []
l2_str = []
for i in l:
  if type(i) == int or type(i) == float:
    l1_num.append(i)
  else :
    l2_str.append(i)

l1_num

l2_str

